### ISSUE TITLE
Camera stream

### ISSUE THREAD

**Issue by valentinitnelav** [PAIcam/PAIcam#1]
The react-native-camera library will allow you to access the camera and capture images, while react-native-image-crop-picker can help you crop the images.

If you want to allow the user to select a rectangle for cropping, react-native-image-crop-picker is an excellent choice as it provides a UI component for cropping that allows the user to select the area they wish to crop. It also supports storing images on the device's storage.

Here's a very basic example of how you could implement this:

```javascript
import React from 'react';
import { Button } from 'react-native';
import { RNCamera } from 'react-native-camera';
import ImagePicker from 'react-native-image-crop-picker';

class CameraComponent extends React.Component {
  takePicture = async function(camera) {
    const options = { quality: 0.5, base64: true };
    const data = await camera.takePictureAsync(options);

    // data.uri should contain the path to the image
    // let the user crop the image
    ImagePicker.openCropper({
      path: data.uri,
      width: 300,
      height: 400,
    }).then(image => {
      console.log(image.path); // contains the path to the cropped image
    });
  };

  render() {
    return (
      <RNCamera
        ref={ref => {
          this.camera = ref;
        }}
        style={{
          flex: 1,
          justifyContent: 'flex-end',
          alignItems: 'center',
        }}>
        <Button
          title="Take photo"
          onPress={() => this.takePicture(this.camera)}
        />
      </RNCamera>
    );
  }
}

```

**Comment by andreglock** [comment]
```
 ERROR  TypeError: Cannot read property 'openPicker' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.     
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by andreglock** [comment]
return (<View>
    <RNCamera
        ref={ref => ref}
        style={{
          flex: 1,
          justifyContent: 'flex-end',
          alignItems: 'center',
        }}>
        <Button
          title="Take photo"
          onPress={() => takePicture(ref)}
        />
      </RNCamera>
  </View>)

**Comment by valentinitnelav** [comment]
Here's how you could convert the class component into a functional component using React hooks:

```javascript
import React, { useRef } from 'react';
import { Button } from 'react-native';
import { RNCamera } from 'react-native-camera';
import ImagePicker from 'react-native-image-crop-picker';

const CameraComponent = () => {
  const cameraRef = useRef(null);

  const takePicture = async () => {
    if (cameraRef.current) {
      const options = { quality: 0.5, base64: true };
      const data = await cameraRef.current.takePictureAsync(options);
      // data.uri should contain the path to the image
      // let the user crop the image
      ImagePicker.openCropper({
        path: data.uri,
        width: 300,
        height: 400,
      }).then(image => {
        console.log(image.path); // contains the path to the cropped image
      });
    }
  };

  return (
    <RNCamera
      ref={cameraRef}
      style={{
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
      }}>
      <Button
        title="Take photo"
        onPress={takePicture}
      />
    </RNCamera>
  );
};

export default CameraComponent;
```

**Comment by andreglock** [comment]
```
Android Bundling complete 72ms
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at ?anon_0_ (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:101526:74)
    at next (native)
    at asyncGeneratorStep (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29651:26)
    at _callTimer (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29570:17)
    at _callReactNativeMicrotasksPass (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29600:17)
    at callReactNativeMicrotasks (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29763:44)
    at __callReactNativeMicrotasks (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2793:46)
    at anonymous (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2605:45)
    at __guard (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2777:15)
    at flushedQueue (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2604:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.233.60.86:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2598:33)
```

**Comment by valentinitnelav** [comment]
There seem to be two issues here:

Deprecation of PropTypes: The warning message "ViewPropTypes will be removed from React Native, along with all other PropTypes" indicates that one of the libraries (or your own code) is using ViewPropTypes which has been deprecated in recent versions of React Native. PropTypes is a way of type checking in React, which is now being replaced with TypeScript or other static typing methods. If you're using PropTypes, consider migrating your code to TypeScript or at least removing usage of ViewPropTypes. If a third-party library is causing this warning, consider updating the library or finding an alternative.

Unhandled Promise Rejection and TypeError: The error "Possible Unhandled Promise Rejection" is occurring because somewhere in your code a Promise is being rejected and that rejection is not being caught and handled. This could be happening in the takePicture function where we are calling takePictureAsync and ImagePicker.openCropper without any catch blocks. Here's how you might add error handling:

```javascript
const takePicture = async () => {
  if (cameraRef.current) {
    try {
      const options = { quality: 0.5, base64: true };
      const data = await cameraRef.current.takePictureAsync(options);

      // data.uri should contain the path to the image
      // let the user crop the image
      ImagePicker.openCropper({
        path: data.uri,
        width: 300,
        height: 400,
      }).then(image => {
        console.log(image.path); // contains the path to the cropped image
      }).catch(error => {
        console.error("Error cropping the image:", error);
      });
    } catch (error) {
      console.error("Error taking picture:", error);
    }
  }
};
```
The TypeError: undefined is not a function, suggests that a function is being called on an undefined object. This might be due to react-native-camera or react-native-image-crop-picker not being properly linked or installed in your project. Ensure that you have followed the installation and linking steps correctly for these libraries.

Also, make sure you've requested the necessary permissions to access the camera and storage.

Finally, if none of these steps help, please provide more context or isolate the part of your code that is causing the problem so that I can provide a more accurate solution.

**Comment by valentinitnelav** [comment]
Here's how the same functional component would look without using arrow functions:

```javascript
import React, { useRef } from 'react';
import { Button } from 'react-native';
import { RNCamera } from 'react-native-camera';
import ImagePicker from 'react-native-image-crop-picker';

function CameraComponent() {
  const cameraRef = useRef(null);

  function takePicture() {
    if (cameraRef.current) {
      const options = { quality: 0.5, base64: true };
      cameraRef.current.takePictureAsync(options)
        .then(data => {
          // data.uri should contain the path to the image
          // let the user crop the image
          ImagePicker.openCropper({
            path: data.uri,
            width: 300,
            height: 400,
          }).then(image => {
            console.log(image.path); // contains the path to the cropped image
          });
        });
    }
  };

  return (
    <RNCamera
      ref={cameraRef}
      style={{
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
      }}>
      <Button
        title="Take photo"
        onPress={takePicture}
      />
    </RNCamera>
  );
};

export default CameraComponent;

````

**Comment by valentinitnelav** [comment]
Here is a possible example using react-native-vision-camera:

```javascript
import React, { useState } from 'react';
import { StyleSheet, View, TouchableOpacity, Text } from 'react-native';
import { Camera } from 'react-native-vision-camera';
import { useCameraDevices } from 'react-native-vision-camera/hooks';
import RNFS from 'react-native-fs';

export default function App() {
  // get the camera devices
  const devices = useCameraDevices('wide-angle-camera');
  const device = devices.back;

  // state for the image uri
  const [imageUri, setImageUri] = useState(null);

  // function to capture and crop the image
  const captureAndCropImage = async () => {
    if (device == null) return;
    // capture the image
    const photo = await cameraRef.current.takePhoto({
      quality: 1,
      skipMetadata: false,
      enableAutoStabilization: true,
      enableDepthData: true,
    });
    // crop the image by user defined dimensions
    // for example, crop a square of 200x200 pixels from the center
    const croppedPhoto = await photo.crop({
      x: (photo.width - 200) / 2,
      y: (photo.height - 200) / 2,
      width: 200,
      height: 200,
    });
    // store the image to SD card
    const path = `${RNFS.ExternalStorageDirectoryPath}/cropped-image.jpg`;
    await RNFS.writeFile(path, croppedPhoto.base64EncodedString, 'base64');
    // set the image uri state
    setImageUri(path);
  };

  // reference to the camera component
  const cameraRef = React.useRef(null);

  return (
    <View style={styles.container}>
      <Camera
        ref={cameraRef}
        style={styles.camera}
        device={device}
        isActive={true}
        photo={true}
      />
      <TouchableOpacity style={styles.button} onPress={captureAndCropImage}>
        <Text style={styles.buttonText}>Capture and Crop</Text>
      </TouchableOpacity>
      {imageUri && (
        <Text style={styles.text}>Image saved to {imageUri}</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  camera: {
    flex: 1,
    width: '100%',
  },
  button: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    borderRadius: 5,
    margin: 10,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  text: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
  },
});
```


Here is a possible minimal and simple version:

```javascript
import React from 'react';
import { Camera } from 'react-native-vision-camera';
import { useCameraDevices } from 'react-native-vision-camera/hooks';
import RNFS from 'react-native-fs';

export default function App() {
  // get the camera device
  const device = useCameraDevices('wide-angle-camera').back;

  // function to capture and crop the image
  const captureAndCropImage = async (camera) => {
    // capture the image
    const photo = await camera.takePhoto();
    // crop the image by user defined dimensions
    const croppedPhoto = await photo.crop({ x: 100, y: 100, width: 200, height: 200 });
    // store the image to SD card
    await RNFS.writeFile(`${RNFS.ExternalStorageDirectoryPath}/cropped-image.jpg`, croppedPhoto.base64EncodedString, 'base64');
  };

  return (
    <Camera
      style={{ flex: 1 }}
      device={device}
      isActive={true}
      photo={true}
      onDoubleTap={captureAndCropImage}
    />
  );
}

```

**Comment by valentinitnelav** [comment]
The react-native-vision-camera/hooks module does not exist. You should use useCameraDevices from react-native-vision-camera instead. Here is the corrected code:

```javascript
import React from 'react';
import { Camera, useCameraDevices } from 'react-native-vision-camera';
import RNFS from 'react-native-fs';

export default function App() {
  // get the camera device
  const device = useCameraDevices('wide-angle-camera').back;

  // function to capture and crop the image
  const captureAndCropImage = async (camera) => {
    // capture the image
    const photo = await camera.takePhoto();
    // crop the image by user defined dimensions
    const croppedPhoto = await photo.crop({ x: 100, y: 100, width: 200, height: 200 });
    // store the image to SD card
    await RNFS.writeFile(`${RNFS.ExternalStorageDirectoryPath}/cropped-image.jpg`, croppedPhoto.base64EncodedString, 'base64');
  };

  return (
    <Camera
      style={{ flex: 1 }}
      device={device}
      isActive={true}
      photo={true}
      onDoubleTap={captureAndCropImage}
    />
  );
}
```

**Comment by valentinitnelav** [comment]
We'll use expo - see Andre's commit 058bbb6
